# -*- coding: utf-8 -*-
"""RAG_Customer_Support_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBiqHFsvRcS2M_RuaXCFljifyiYI-Wfx
"""

!pip install -q langchain langchain-core langchain-community langchain-openai langchain-classic chromadb sentence-transformers zstd

!curl -fsSL https://ollama.com/install.sh | sh


!nohup ollama serve > ollama.log 2>&1 &


import time
time.sleep(5)

!ollama pull qwen2.5:3b

print("Ollama & Qwen 2.5 are successfully ready!")

!pip install -q --upgrade langchain langchain-core langchain-community langchain-openai chromadb sentence-transformers

import os

kb_content = """# Sharkbay.shop - Official Enterprise Knowledge Base & Customer Support Manual

## 1. Company Overview & Core Value Proposition
- **About Us**: sharkbay.shop is Malta's premier localized e-commerce platform, designed to be the "Amazon of Malta". We are built locally for the local community, offering an extensive product catalog, hyper-fast delivery, and competitive pricing.
- **Local Infrastructure**: Unlike overseas platforms facing customs delays and high shipping fees, our dedicated local warehouse is based right here in Malta, ensuring immediate inventory processing, local pickups, and seamless island-wide distribution.

## 2. Shipping, Fulfillment & Delivery Policy
- **Warehouse Local Pickup (100% Free)**:
  - Customers can choose free local pickup at our warehouse with zero shipping fees, regardless of order amount.
  - **Warehouse Address**: San Pawl, Triq MRU Giorgio Zarb, Qormi.
- **Same-Day Delivery (Door-to-Door / Home Delivery)**:
  - Available for orders placed before the daily cut-off time.
  - **Free Shipping Threshold**: **FREE home delivery** for orders over **EUR 49**.
- **Next-Day Delivery / Standard Delivery (Door-to-Door / Home Delivery)**:
  - **Free Shipping Threshold**: **FREE home delivery** for orders over **EUR 29**.
- **Coverage**: We proudly deliver island-wide across both **Malta and Gozo**.

## 3. Product Categories & Assortment
- sharkbay.shop features a comprehensive multi-category catalog, catering to everyday lifestyle needs:
  - Electronics & Smart Home Devices
  - Home & Kitchen Essentials
  - Fashion & Daily Wear
  - Beauty, Health & Personal Care
  - Local Specialty & Seasonal Goods

## 4. Returns, Refunds & Customer Support
- **Return Policy**: Customers in Malta can return unused and original-packaged items within 14 days of delivery for a hassle-free full refund or exchange.
- **Support Channels**:
  - 24/7 AI-powered automated support chat (via our website live agent).
  - Human customer service team available Monday to Saturday, 9:00 AM - 6:00 PM CET.
  - Email & automated webhook escalation for urgent order or fulfillment inquiries.
"""

with open("sharkbay_knowledge_base.md", "w", encoding="utf-8") as f:
    f.write(kb_content)

print(" Knowledge base file 'sharkbay_knowledge_base.md' generated successfully!")

import os
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.vectorstores import Chroma
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

def build_local_rag_system():
    print("1. Loading Sharkbay Knowledge Base...")
    loader = TextLoader("sharkbay_knowledge_base.md", encoding="utf-8")
    raw_documents = loader.load()

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    docs = text_splitter.split_documents(raw_documents)


    print("2. Generating local embeddings...")
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    vectorstore = Chroma.from_documents(docs, embeddings)
    retriever = vectorstore.as_retriever(search_kwargs={"k": 2})


    system_prompt = (
        "You are the official AI customer support and shopping assistant for **sharkbay.shop**, "
        "Malta's premier localized e-commerce platform. "
        "Carefully distinguish between 'Warehouse Local Pickup' (always free at Qormi) and 'Door-to-Door Home Delivery'. "
        "For Same-Day home delivery, it is free for orders over EUR 49. For Next-Day home delivery, it is free for orders over EUR 29. "
        "Answer customer questions accurately based strictly on this context.\n\n"
        "Context:\n{context}"
    )
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])


    print("3. Connecting to local Ollama (Qwen 2.5)...")
    OLLAMA_BASE_URL = "http://localhost:11434/v1"
    llm = ChatOpenAI(
        model="qwen2.5:3b",
        temperature=0.3,
        openai_api_base=OLLAMA_BASE_URL,
        openai_api_key="ollama"
    )

    def format_docs(docs):
        return "\n\n".join(doc.page_content for doc in docs)


    rag_chain = (
        {"context": retriever | format_docs, "input": RunnablePassthrough()}
        | prompt
        | llm
        | StrOutputParser()
    )

    return rag_chain


rag_system = build_local_rag_system()
print("\n Local RAG System is fully initialized and ready!\n" + "="*50)

test_queries = [
    "Where is your warehouse located for local pickup?",
    "How much do I need to spend for free same-day delivery?",
]

for query in test_queries:
    print(f"[Customer]: {query}")
    response = rag_system.invoke(query)
    print(f"[Sharkbay AI]: {response}\n" + "-"*50)

"""Backend API wrapper"""

!pip install fastapi uvicorn nest-asyncio -q

from fastapi import FastAPI
from pydantic import BaseModel
import nest_asyncio
import uvicorn


app = FastAPI(title="Sharkbay AI Support API")


class ChatRequest(BaseModel):
    message: str


@app.post("/api/chat")
async def chat_with_ai(request: ChatRequest):

    answer = rag_system.invoke(request.message)
    return {"reply": answer}

print("FastAPI backend wrapper is ready!")

# Run ollama
!nohup ollama serve > ollama.log 2>&1 &

# Run the model
!ollama run qwen2.5:3b "Hello"

import threading
import uvicorn

def run_server():
    # Start the FastAPI server on localhost:8000
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="info")

# Create a background thread to run the FastAPI server
server_thread = threading.Thread(target=run_server, daemon=True)
server_thread.start()

print("🚀 FastAPI backend server has successfully started and is running in a background thread!")
print("👉 You can now visit: http://127.0.0.1:8000/docs for interactive web testing.")

!npm install -g localtunnel -q


!npx localtunnel --port 8000